#This action is from: https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards

name: Issue Automation
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress when a developer is assigned
        uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Chirp
          column: In Progress
          repo-token: ${{ secrets.ISSUE_AUTOMATION }}
