#This action is from: https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
name: "Issue States"

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v3
        with:
          github-token: ${{ secrets.ISSUE_AUTOMATION }}
          open-issue-columns: ""
          closed-issue-columns: "Closed, Done"
          log-output: false
